import logo from './assets/logo-to-use.png'
import bgimage from './assets/bg_image.jpg'
import starRating from './assets/star-ratings.svg'
import webImage from './assets/website.jpg'
import appImage from './assets/app-dev.jpg'
import softwareImage from './assets/software.jpg'
import portfolioImage from './assets/portfolio.jpg'
import aboutusImage from './assets/aboutus.jpg'
import whyUsImage from './assets/whyus.jpg'
import tick from './assets/tick.svg'
import contact1 from './assets/contact1.jpg'
import contact2 from './assets/contact2.jpg'
import contact3 from './assets/contact3.jpg'

export { logo, bgimage, starRating, webImage, appImage, softwareImage, portfolioImage, aboutusImage, whyUsImage, tick, contact1, contact2, contact3 }